path:
  datasets_dir: datasets
  background_dir: backgrounds
  demo_dir_name: demo_stuff
  demo_output_name: predicted
  image_dir_name: images
  dataset_info_file: dataset_info.yaml

  models_dir: models
  model_ckpt_name: ckpt
  model_configs_name: configs
  model_yaml_name: params.yaml

  labelme_annotation_name: labelme_annotations
  labelme_segment_annotation_name: labelme_segment_annotations
  object_dir_name: objects
  coco_annotaton_name: coco_annotations
  coco_annotaton_file: annotation.json